apiVersion: apps/v1
kind: Deployment

metadata:
  name: static-site

spec:
  replicas: 2

  selector:
    matchLabels:
      app: static-site

  template:
    metadata:
      labels:
        app: static-site

    spec:
      containers:
      - name: website
        image: fedsatya/gobaconstructions-github-actions-argocd-on-minikube:2fabf1c24c40790a197311d6781647d4e0527390
        ports:
        - containerPort: 80
